#%RAML 0.8
title: Test Query API
baseUri: http://localhost:3000/test
protocols: [ HTTP, HTTPS ]

/get-endpoint:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/example.json